### ISSUE TITLE
Sign-up with email verification

### ISSUE THREAD

**Issue by iahmed93** [iahmed93/bosta_assessment#1]
### Tasks:
- [x] Create Nodejs + Express + Mongoose Project
- [x] Create sign-up API
- [x] Verify Email format 
- [x] Hash The Password
- [x] Generate email verification code
- [x] Save the user using mongoose
- [x] Create send email service
- [x] Send Email on successful sign-up with a code auto generated
- [x] Create verify email API which check if the sent code is matched or not 

### User Data: 
- Email
- Password
- IsVerified (default is false)
- EmailVerificationCode

### Resources: 

- https://blog.tericcabrel.com/set-up-a-nodejs-project-with-typescript-eslint-and-prettier/
- https://blog.tericcabrel.com/create-a-rest-api-with-nodejs-express-mongodb-and-typescript/
- https://blog.logrocket.com/typescript-with-node-js-and-express/
- https://www.npmjs.com/package/nodemailer
- https://nodemailer.com/about/
- https://blog.tericcabrel.com/use-mongodb-with-node-js/
- https://mongoosejs.com/docs/index.html
- https://www.w3schools.com/nodejs/nodejs_email.asp
- https://stackoverflow.com/questions/37167602/typescript-node-js-express-routes-separated-files-best-practices
- https://dev.to/francis04j/how-to-add-env-and-use-process-env-to-your-typescript-project-3d6b
- https://ethereal.email/messages
