### ISSUE TITLE
Stateless authentication using JWT

### ISSUE THREAD

**Issue by iahmed93** [iahmed93/bosta_assessment#2]
### Tasks
- [x] add the tokens array to the user model in mongoose
- [x] create token service with email as payload and add it to the user's token array
- [x] send the token back to the user
- [x] create verify token service
- [x] add middleware to verify authorize bearer token

### Resources
- https://www.section.io/engineering-education/how-to-build-authentication-api-with-jwt-token-in-nodejs/
