### ISSUE TITLE
Users can create a check to monitor a given URL if it is up or down

### ISSUE THREAD

**Issue by iahmed93** [iahmed93/bosta_assessment#3]
### Tasks:

- [x] create the check api
- [x] save the configuration to the db
- [x] start the scheduled checker
- [x] send http(s) request
- [x] send tcp request
- [x] save the checker result to the db
- [x] start all active checks on starting the server

###  Each check may have the following options:
  - `name` - The name of the check.
  - `url` - The URL to be monitored.
  - `protocol` - The resource protocol name `HTTP`, `HTTPS`, or `TCP`.
  - `path` - A specific path to be monitored (optional).
  - `port` - The server port number (optional).
  - `webhook` - A webhook URL to receive a notification on (optional).
  - `timeout` (defaults to 5 seconds) - The timeout of the polling request (optional).
  - `interval` (defaults to 10 minutes) - The time interval for polling requests (optional).
  - `threshold` (defaults to 1 failure) - The threshold of failed requests that will create an alert (optional).
  - `authentication` - An HTTP authentication header, with the Basic scheme, to be sent with the polling request (optional).
    - `authentication.username`
    - `authentication.password`
  - `httpHeaders` - A list of key/value pairs custom HTTP headers to be sent with the polling request (optional).
  - `assert` - The response assertion to be used on the polling response (optional).
    - `assert.statusCode`: An HTTP status code to be asserted.
  - `tags` - A list of the check tags (optional).
  - `ignoreSSL` - A flag to ignore broken/expired SSL certificates in case of using the HTTPS protocol.
  - `status` - default is active

### Resources
https://medium.com/hackernoon/settimeout-vs-setimmediate-vs-process-nexttick-ffafa3b36de2
https://github.com/axios/axios
